//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.Registration.Exporter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaselConventionAndOecdCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaselConventionAndOecdCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.Registration.Exporter.BaselConvention" +
                            "AndOecdCodes", typeof(BaselConventionAndOecdCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codes for the {0} packaging waste you export to this site.
        /// </summary>
        public static string codes_for_materialname_export_to_site_subheading {
            get {
                return ResourceManager.GetString("codes_for_materialname_export_to_site_subheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use them to describe the packaging waste you&apos;re exporting to this reprocessing site..
        /// </summary>
        public static string consolidated_waste_list_help_text {
            get {
                return ResourceManager.GetString("consolidated_waste_list_help_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ll find the codes on the &lt;a href=&quot;https://www.gov.uk/government/publications/waste-shipments-regulation-wsr-consolidated-waste-list&quot; target=&quot;_blank&quot; class=&quot;govuk-link&quot;&gt;consolidated waste list (opens in new tab)&lt;/a&gt;.
        /// </summary>
        public static string consolidated_waste_list_link_with_description {
            get {
                return ResourceManager.GetString("consolidated_waste_list_link_with_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter one or more codes.
        /// </summary>
        public static string enter_one_or_more_codes {
            get {
                return ResourceManager.GetString("enter_one_or_more_codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basel Convention and OECD codes.
        /// </summary>
        public static string page_description {
            get {
                return ResourceManager.GetString("page_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basel Convention and OECD codes.
        /// </summary>
        public static string page_title {
            get {
                return ResourceManager.GetString("page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Basel Convention or OECD code.
        /// </summary>
        public static string ValidationMessage_OecdCodes_MustEnteredAtleastOneCode {
            get {
                return ResourceManager.GetString("ValidationMessage_OecdCodes_MustEnteredAtleastOneCode", resourceCulture);
            }
        }
    }
}
