//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.Registration.Exporter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OverseasSiteDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OverseasSiteDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.Registration.Exporter.OverseasSiteDet" +
                            "ails", typeof(OverseasSiteDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be able to add more sites after you&apos;ve added this one..
        /// </summary>
        public static string AddMoreSitesInfo {
            get {
                return ResourceManager.GetString("AddMoreSitesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1.
        /// </summary>
        public static string AddressLine1Label {
            get {
                return ResourceManager.GetString("AddressLine1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1 must be 100 characters or fewer.
        /// </summary>
        public static string AddressLine1MaxLength {
            get {
                return ResourceManager.GetString("AddressLine1MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address line 1, typically the building and street.
        /// </summary>
        public static string AddressLine1Required {
            get {
                return ResourceManager.GetString("AddressLine1Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2 (optional).
        /// </summary>
        public static string AddressLine2Label {
            get {
                return ResourceManager.GetString("AddressLine2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2 must be 100 characters or fewer.
        /// </summary>
        public static string AddressLine2MaxLength {
            get {
                return ResourceManager.GetString("AddressLine2MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a country.
        /// </summary>
        public static string ChooseCountry {
            get {
                return ResourceManager.GetString("ChooseCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City or town.
        /// </summary>
        public static string CityorTownLabel {
            get {
                return ResourceManager.GetString("CityorTownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City or town must be 70 characters or fewer.
        /// </summary>
        public static string CityorTownMaxLength {
            get {
                return ResourceManager.GetString("CityorTownMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a city or town.
        /// </summary>
        public static string CityorTownRequired {
            get {
                return ResourceManager.GetString("CityorTownRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This must be a person holding a senior position in the organisation.
        /// </summary>
        public static string ContactFullNameHint {
            get {
                return ResourceManager.GetString("ContactFullNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name of person the regulator can contact.
        /// </summary>
        public static string ContactFullNameLabel {
            get {
                return ResourceManager.GetString("ContactFullNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name must be 100 characters or fewer.
        /// </summary>
        public static string ContactFullNameMaxLength {
            get {
                return ResourceManager.GetString("ContactFullNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the person the regulator can contact.
        /// </summary>
        public static string ContactFullNameRequired {
            get {
                return ResourceManager.GetString("ContactFullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country the site is in.
        /// </summary>
        public static string CountryLabel {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the country the site is in.
        /// </summary>
        public static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an email address in the correct format, like name@example.com.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be 100 characters or fewer.
        /// </summary>
        public static string EmailMaxLength {
            get {
                return ResourceManager.GetString("EmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email of the person the regulator can contact.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation name.
        /// </summary>
        public static string OrganisationNameLabel {
            get {
                return ResourceManager.GetString("OrganisationNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the organisation’s name.
        /// </summary>
        public static string OrganisationNameRequired {
            get {
                return ResourceManager.GetString("OrganisationNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumberLabel {
            get {
                return ResourceManager.GetString("PhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must be 25 characters or fewer.
        /// </summary>
        public static string PhoneNumberMaxLength {
            get {
                return ResourceManager.GetString("PhoneNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phone number of the person the regulator can contact.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some countries use only numbers, others use a mix of letters and numbers. Leave blank if the country does not have postcodes
        ///.
        /// </summary>
        public static string PostcodeHint {
            get {
                return ResourceManager.GetString("PostcodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode or similar (optional).
        /// </summary>
        public static string PostcodeLabel {
            get {
                return ResourceManager.GetString("PostcodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode must be 20 characters or fewer.
        /// </summary>
        public static string PostcodeMaxLength {
            get {
                return ResourceManager.GetString("PostcodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude and longitude coordinates for the site’s main entrance.
        /// </summary>
        public static string SiteCoordinatesHint {
            get {
                return ResourceManager.GetString("SiteCoordinatesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude and longitude coordinates for the site’s main entrance.
        /// </summary>
        public static string SiteCoordinatesLabel {
            get {
                return ResourceManager.GetString("SiteCoordinatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates must be 100 characters or fewer.
        /// </summary>
        public static string SiteCoordinatesMaxLength {
            get {
                return ResourceManager.GetString("SiteCoordinatesMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the latitude and longitude coordinates for the site’s main entrance.
        /// </summary>
        public static string SiteCoordinatesRequired {
            get {
                return ResourceManager.GetString("SiteCoordinatesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank if the address does not have a state, province or region.
        /// </summary>
        public static string StateProvinceHint {
            get {
                return ResourceManager.GetString("StateProvinceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State, province or region (optional).
        /// </summary>
        public static string StateProvinceLabel {
            get {
                return ResourceManager.GetString("StateProvinceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State, province or region must be 70 characters or fewer.
        /// </summary>
        public static string StateProvinceMaxLength {
            get {
                return ResourceManager.GetString("StateProvinceMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter details for first overseas reprocessing site.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter overseas reprocessing site details.
        /// </summary>
        public static string Title2 {
            get {
                return ResourceManager.GetString("Title2", resourceCulture);
            }
        }
    }
}
