//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.Shared.Partials {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MaterialPermitInput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaterialPermitInput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.Shared.Partials.MaterialPermitInput", typeof(MaterialPermitInput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select if the authorised weight is per year, per month or per week.
        /// </summary>
        public static string frequency_option_required_error_message {
            get {
                return ResourceManager.GetString("frequency_option_required_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this per year, per month or per week?.
        /// </summary>
        public static string frequency_options_label_text {
            get {
                return ResourceManager.GetString("frequency_options_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight must be a number, like 100.
        /// </summary>
        public static string maximum_weight_format_error_message {
            get {
                return ResourceManager.GetString("maximum_weight_format_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum weight of {0} the permit authorises the site to accept and recycle.
        /// </summary>
        public static string maximum_weight_label_text {
            get {
                return ResourceManager.GetString("maximum_weight_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum weight of {0} the licence authorises the site to accept and recycle.
        /// </summary>
        public static string maximum_weight_licence_label_text {
            get {
                return ResourceManager.GetString("maximum_weight_licence_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight must be a number less than 10,000,000.
        /// </summary>
        public static string maximum_weight_maximum_error_message {
            get {
                return ResourceManager.GetString("maximum_weight_maximum_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight must be a number greater than 0.
        /// </summary>
        public static string maximum_weight_minimum_error_message {
            get {
                return ResourceManager.GetString("maximum_weight_minimum_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the maximum weight the permit authorises the site to accept and recycle.
        /// </summary>
        public static string maximum_weight_required_error_message {
            get {
                return ResourceManager.GetString("maximum_weight_required_error_message", resourceCulture);
            }
        }
    }
}
