//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.FileUpload {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileUpload {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileUpload() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.FileUpload.FileUpload", typeof(FileUpload).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file contains a virus.
        /// </summary>
        internal static string selected_file_contains_virus {
            get {
                return ResourceManager.GetString("selected_file_contains_virus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file is empty.
        /// </summary>
        internal static string selected_file_is_empty {
            get {
                return ResourceManager.GetString("selected_file_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file must be smaller than {0}MB.
        /// </summary>
        internal static string selected_file_must_be_smaller_than {
            get {
                return ResourceManager.GetString("selected_file_must_be_smaller_than", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file must be PDF, DOC, DOCX, XLS, XLSX, CSV, PNG, TIF, JPG or MSG.
        /// </summary>
        internal static string selected_file_must_be_valid_file_type {
            get {
                return ResourceManager.GetString("selected_file_must_be_valid_file_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file name cannot be empty.
        /// </summary>
        internal static string selected_filename_cannot_be_empty {
            get {
                return ResourceManager.GetString("selected_filename_cannot_be_empty", resourceCulture);
            }
        }
    }
}
