//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.ExporterJourney.OtherPermits {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CheckAnswers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CheckAnswers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.ExporterJourney.OtherPermits.CheckYourAnswers", typeof(CheckAnswers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People you want to request authority to issue PRNs.
        /// </summary>
        internal static string authority_label {
            get {
                return ResourceManager.GetString("authority_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your answers before continuing.
        /// </summary>
        internal static string main_heading {
            get {
                return ResourceManager.GetString("main_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over 10,000 tonnes.
        /// </summary>
        internal static string over_10000_tonnes {
            get {
                return ResourceManager.GetString("over_10000_tonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonnage of PRNs you plan to issue.
        /// </summary>
        internal static string prn_tonnage_label {
            get {
                return ResourceManager.GetString("prn_tonnage_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your answers.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 1,000 tonnes.
        /// </summary>
        internal static string up_to_1000_tonnes {
            get {
                return ResourceManager.GetString("up_to_1000_tonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 10,000 tonnes.
        /// </summary>
        internal static string up_to_10000_tonnes {
            get {
                return ResourceManager.GetString("up_to_10000_tonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to up to 500 tonnes.
        /// </summary>
        internal static string up_to_500_tonnes {
            get {
                return ResourceManager.GetString("up_to_500_tonnes", resourceCulture);
            }
        }
    }
}
