//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.ExporterJourney.OtherPermits {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OtherPermits {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OtherPermits() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.ExporterJourney.OtherPermits.OtherPer" +
                            "mits", typeof(OtherPermits).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the reference number for any other permits and exemptions you have..
        /// </summary>
        public static string caption {
            get {
                return ResourceManager.GetString("caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation permit or Pollution Prevention and Control (PPC) permit number.
        /// </summary>
        public static string installation_permit_or_ppc_number {
            get {
                return ResourceManager.GetString("installation-permit-or-ppc-number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank if you do not have one.
        /// </summary>
        public static string leave_blank_if_you_do_not_have_one {
            get {
                return ResourceManager.GetString("leave-blank-if-you-do-not-have-one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of license / reference number must be 50 characters or less..
        /// </summary>
        public static string maximum_permit_ref_length {
            get {
                return ResourceManager.GetString("maximum_permit_ref_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the reference number for any other permits and exemptions you have..
        /// </summary>
        public static string page_description {
            get {
                return ResourceManager.GetString("page_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other permits.
        /// </summary>
        public static string page_title {
            get {
                return ResourceManager.GetString("page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste exemption reference.
        /// </summary>
        public static string waste_exemption_reference {
            get {
                return ResourceManager.GetString("waste-exemption-reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste management license or environmental permit number.
        /// </summary>
        public static string waste_management_license_or_permit_number {
            get {
                return ResourceManager.GetString("waste-management-license-or-permit-number", resourceCulture);
            }
        }
    }
}
