//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.Accreditation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BusinessPlan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessPlan() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.Accreditation.BusinessPlan", typeof(BusinessPlan).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communications, including information campaigns.
        /// </summary>
        internal static string communications {
            get {
                return ResourceManager.GetString("communications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developing new markets for products made from recycled packaging waste.
        /// </summary>
        internal static string developing_new_markets {
            get {
                return ResourceManager.GetString("developing_new_markets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developing new uses for recycled waste.
        /// </summary>
        internal static string developing_new_uses_for_recycled_waste {
            get {
                return ResourceManager.GetString("developing_new_uses_for_recycled_waste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business plan.
        /// </summary>
        internal static string heading {
            get {
                return ResourceManager.GetString("heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the percentage of steel PRN income you’ll spend on each item..
        /// </summary>
        internal static string lead_para_1 {
            get {
                return ResourceManager.GetString("lead_para_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The regulator will expect you to follow this plan. If you later need to change how you spend the income you must explain this in your annual report..
        /// </summary>
        internal static string lead_para_2 {
            get {
                return ResourceManager.GetString("lead_para_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New reprocessing infrastructure and maintaining existing infrastructure.
        /// </summary>
        internal static string new_reprocessing_infrastructure {
            get {
                return ResourceManager.GetString("new_reprocessing_infrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price support for buying packaging waste or selling recycled packaging waste.
        /// </summary>
        internal static string price_support {
            get {
                return ResourceManager.GetString("price_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support for business collections.
        /// </summary>
        internal static string support_for_business_collections {
            get {
                return ResourceManager.GetString("support_for_business_collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business plan.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Percentage.
        /// </summary>
        internal static string total_percentage {
            get {
                return ResourceManager.GetString("total_percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total must equal 100%.
        /// </summary>
        internal static string warning_total_must_be_100 {
            get {
                return ResourceManager.GetString("warning_total_must_be_100", resourceCulture);
            }
        }
    }
}
