//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.Accreditation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EvidenceOfEquivalentStandardsUploadDocument {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EvidenceOfEquivalentStandardsUploadDocument() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.Accreditation.EvidenceOfEquivalentSta" +
                            "ndardsUploadDocument", typeof(EvidenceOfEquivalentStandardsUploadDocument).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if the document has dates on it.
        /// </summary>
        internal static string check_if_documents {
            get {
                return ResourceManager.GetString("check_if_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are dates to show when the document is valid from and when it expires..
        /// </summary>
        internal static string check_if_documents_sub {
            get {
                return ResourceManager.GetString("check_if_documents_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter expiry date of document.
        /// </summary>
        internal static string document_expire {
            get {
                return ResourceManager.GetString("document_expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank if there&apos;s no expire date.
        /// </summary>
        internal static string document_expire_leave_blank {
            get {
                return ResourceManager.GetString("document_expire_leave_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter date the document is valid from.
        /// </summary>
        internal static string document_valid_from {
            get {
                return ResourceManager.GetString("document_valid_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank if there&apos;s no valid from date.
        /// </summary>
        internal static string document_valid_from_leave_blank {
            get {
                return ResourceManager.GetString("document_valid_from_leave_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now upload the document.
        /// </summary>
        internal static string now_upload_document {
            get {
                return ResourceManager.GetString("now_upload_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload evidence of broadly equivalent standards for: {0}.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upload one piece of evidence now. If you have more evidence you can upload this next..
        /// </summary>
        internal static string upload_details {
            get {
                return ResourceManager.GetString("upload_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now upload the document.
        /// </summary>
        internal static string upload_file {
            get {
                return ResourceManager.GetString("upload_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
    }
}
