//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.Accreditation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TaskList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.Accreditation.TaskList", typeof(TaskList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accreditation sampling and inspection plan.
        /// </summary>
        public static string accreditation_sampling {
            get {
                return ResourceManager.GetString("accreditation_sampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business plan.
        /// </summary>
        public static string business_plan {
            get {
                return ResourceManager.GetString("business_plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANNOT START YET.
        /// </summary>
        public static string cannot_start_yet_status {
            get {
                return ResourceManager.GetString("cannot_start_yet_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETED.
        /// </summary>
        public static string completed_status {
            get {
                return ResourceManager.GetString("completed_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence of broadly equivalent standards.
        /// </summary>
        public static string evidence_of_broadly_equivalent_standards {
            get {
                return ResourceManager.GetString("evidence_of_broadly_equivalent_standards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For reprocessing site: , RHYL COAST ROAD, Rhyl, Denbighshire, .
        /// </summary>
        public static string heading_site {
            get {
                return ResourceManager.GetString("heading_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For: 2026.
        /// </summary>
        public static string heading_year {
            get {
                return ResourceManager.GetString("heading_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN PROGRESS.
        /// </summary>
        public static string in_progress_status {
            get {
                return ResourceManager.GetString("in_progress_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accredit to issue PRNs: UK steel packaging waste.
        /// </summary>
        public static string main_heading {
            get {
                return ResourceManager.GetString("main_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete each section then submit your application to the regulator. You can save your progress and come back to it at any time..
        /// </summary>
        public static string main_para {
            get {
                return ResourceManager.GetString("main_para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT STARTED.
        /// </summary>
        public static string not_started_status {
            get {
                return ResourceManager.GetString("not_started_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overseas reprocessing sites.
        /// </summary>
        public static string overseas_reprocessing_sites {
            get {
                return ResourceManager.GetString("overseas_reprocessing_sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accredit to issue PRNs. Task list.
        /// </summary>
        public static string page_description {
            get {
                return ResourceManager.GetString("page_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRNs tonnage and authority to issue  PRNs.
        /// </summary>
        public static string prn_tonnage {
            get {
                return ResourceManager.GetString("prn_tonnage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string some_people_in_your_organisation_are_responsible {
            get {
                return ResourceManager.GetString("some_people_in_your_organisation_are_responsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string status_completed {
            get {
                return ResourceManager.GetString("status_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accredit to issue PRNs.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string you_cannot_submit_application {
            get {
                return ResourceManager.GetString("you_cannot_submit_application", resourceCulture);
            }
        }
    }
}
