//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SelectOrganisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SelectOrganisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.Home.SelectOrganisation", typeof(SelectOrganisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which organisation’s account do you want to view?.
        /// </summary>
        internal static string SelectOrganisation_Caption {
            get {
                return ResourceManager.GetString("SelectOrganisation.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When an organisation is not on the list, it may be unregistered, or you may not have access to its account..
        /// </summary>
        internal static string SelectOrganisation_DetailsComponentCommonText1 {
            get {
                return ResourceManager.GetString("SelectOrganisation.DetailsComponentCommonText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To proceed, contact the account Administrator and ask to be invited to join the ‘Report packaging data’ service..
        /// </summary>
        internal static string SelectOrganisation_DetailsComponentCommonText2 {
            get {
                return ResourceManager.GetString("SelectOrganisation.DetailsComponentCommonText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an organisation by trading name.
        /// </summary>
        internal static string SelectOrganisation_ErrorMessage {
            get {
                return ResourceManager.GetString("SelectOrganisation.ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an organisation by trading name:.
        /// </summary>
        internal static string SelectOrganisation_HintText {
            get {
                return ResourceManager.GetString("SelectOrganisation.HintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation is not listed.
        /// </summary>
        internal static string SelectOrganisation_OrganisationIsNotListed {
            get {
                return ResourceManager.GetString("SelectOrganisation.OrganisationIsNotListed", resourceCulture);
            }
        }
    }
}
