//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.App.Resources.Enums {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PermitType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PermitType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.App.Resources.Enums.PermitType", typeof(PermitType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmental permit or waste management licence.
        /// </summary>
        public static string environmental_permit_and_waste_management_licence {
            get {
                return ResourceManager.GetString("environmental_permit_and_waste_management_licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation permit.
        /// </summary>
        public static string installation_permit {
            get {
                return ResourceManager.GetString("installation_permit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollution, Prevention and Control (PPC) permit.
        /// </summary>
        public static string ppc_permit {
            get {
                return ResourceManager.GetString("ppc_permit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste exemption.
        /// </summary>
        public static string waste_exemption {
            get {
                return ResourceManager.GetString("waste_exemption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste management licence.
        /// </summary>
        public static string waste_management_licence {
            get {
                return ResourceManager.GetString("waste_management_licence", resourceCulture);
            }
        }
    }
}
