variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'eprrepexpfrontend'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprrepexpfrontendrepository'
  serviceName: 'PRDRWDWEBWA1416'