//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.ReprocessingInputsAndOutputs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReprocessingOutputsForLastYear {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReprocessingOutputsForLastYear() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.ReprocessingInputsAndOutputs.Reproces" +
                            "singOutputsForLastYear", typeof(ReprocessingOutputsForLastYear).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another product.
        /// </summary>
        public static string AddAnotherProduct {
            get {
                return ResourceManager.GetString("AddAnotherProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total contaminants from all {0} reprocessing.
        /// </summary>
        public static string Contaminants_heading {
            get {
                return ResourceManager.GetString("Contaminants_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contaminants removed from the materials during reprocessing, including non-recyclable components or impurities..
        /// </summary>
        public static string Contaminants_heading_desc {
            get {
                return ResourceManager.GetString("Contaminants_heading_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total inputs.
        /// </summary>
        public static string inputsLabel {
            get {
                return ResourceManager.GetString("inputsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total {0} sent on to other sites for reprocessing.
        /// </summary>
        public static string OtherSite_heading {
            get {
                return ResourceManager.GetString("OtherSite_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material received but not reprocessed at your site.
        /// </summary>
        public static string OtherSite_heading_desc {
            get {
                return ResourceManager.GetString("OtherSite_heading_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total outputs.
        /// </summary>
        public static string outputlabel {
            get {
                return ResourceManager.GetString("outputlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a reprocessor of UK packaging waste. Reprocessing outputs for last calendar year.
        /// </summary>
        public static string page_description {
            get {
                return ResourceManager.GetString("page_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs for last calendar year ({0}).
        /// </summary>
        public static string Page_heading {
            get {
                return ResourceManager.GetString("Page_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprocessing outputs for last calendar year.
        /// </summary>
        public static string page_title {
            get {
                return ResourceManager.GetString("page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products made from reprocessing.
        /// </summary>
        public static string ProductsMadeFrom_heading {
            get {
                return ResourceManager.GetString("ProductsMadeFrom_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the names and tonnages of the products.
        /// </summary>
        public static string ProductsMadeFrom_heading_desc {
            get {
                return ResourceManager.GetString("ProductsMadeFrom_heading_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter tonnages for your reprocessing outputs..
        /// </summary>
        public static string tonnage_empty_error {
            get {
                return ResourceManager.GetString("tonnage_empty_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a tonnage greater than 0..
        /// </summary>
        public static string tonnage_lower_bound_error {
            get {
                return ResourceManager.GetString("tonnage_lower_bound_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight must be 10,000,000 tonnes or less..
        /// </summary>
        public static string tonnage_upper_bound_error {
            get {
                return ResourceManager.GetString("tonnage_upper_bound_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter tonnages in whole numbers, like 10.
        /// </summary>
        public static string tonnage_whole_number_error {
            get {
                return ResourceManager.GetString("tonnage_whole_number_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total process loss from all {0} reprocessing.
        /// </summary>
        public static string Totalloss_heading {
            get {
                return ResourceManager.GetString("Totalloss_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, loss through material degradation or waste.
        /// </summary>
        public static string Totalloss_heading_desc {
            get {
                return ResourceManager.GetString("Totalloss_heading_desc", resourceCulture);
            }
        }
    }
}
