//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.ReprocessingInputsAndOutputs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.ReprocessingInputsAndOutputs.Validati" +
                            "onErrors", typeof(ValidationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of a Product..
        /// </summary>
        public static string product_name_empty_error {
            get {
                return ResourceManager.GetString("product_name_empty_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product must be less than 50 characters..
        /// </summary>
        public static string product_name_length_error {
            get {
                return ResourceManager.GetString("product_name_length_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product must be written using letters..
        /// </summary>
        public static string product_name_non_alpha_error {
            get {
                return ResourceManager.GetString("product_name_non_alpha_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a tonnage for the Product..
        /// </summary>
        public static string product_tonnage_empty_error {
            get {
                return ResourceManager.GetString("product_tonnage_empty_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight must be greater than 0.
        /// </summary>
        public static string product_tonnage_lower_bound_error {
            get {
                return ResourceManager.GetString("product_tonnage_lower_bound_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight must be 10,000,000 tonnes or less..
        /// </summary>
        public static string product_tonnage_upper_bound_error {
            get {
                return ResourceManager.GetString("product_tonnage_upper_bound_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter tonnages in whole numbers, like 10..
        /// </summary>
        public static string product_tonnage_whole_number_error {
            get {
                return ResourceManager.GetString("product_tonnage_whole_number_error", resourceCulture);
            }
        }
    }
}
