//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.Registration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddressForNotices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddressForNotices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.Registration.AddressForNotices", typeof(AddressForNotices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The business address.
        /// </summary>
        public static string BusinessAddress {
            get {
                return ResourceManager.GetString("BusinessAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a different address.
        /// </summary>
        public static string DifferentAddress {
            get {
                return ResourceManager.GetString("DifferentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registered address.
        /// </summary>
        public static string RegisteredAddress {
            get {
                return ResourceManager.GetString("RegisteredAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are notices setting out the conditions of your registration or registrations. They could also be enforcement or compliance notices..
        /// </summary>
        public static string regulator_address_for_notices_description {
            get {
                return ResourceManager.GetString("regulator_address_for_notices_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At which address should the regulator serve notices?.
        /// </summary>
        public static string regulator_address_for_notices_title {
            get {
                return ResourceManager.GetString("regulator_address_for_notices_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an address for service of notices..
        /// </summary>
        public static string select_the_address_for_notifications {
            get {
                return ResourceManager.GetString("select_the_address_for_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site address.
        /// </summary>
        public static string SiteAddress {
            get {
                return ResourceManager.GetString("SiteAddress", resourceCulture);
            }
        }
    }
}
