//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.Registration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CarrierBrokerDealer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CarrierBrokerDealer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.Registration.CarrierBrokerDealer", typeof(CarrierBrokerDealer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does {0} have a waste, broker or dealer registration?.
        /// </summary>
        internal static string does_company_have_waste_broker_dealer_registration {
            get {
                return ResourceManager.GetString("does_company_have_waste_broker_dealer_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter registration number.
        /// </summary>
        internal static string enter_registration_number {
            get {
                return ResourceManager.GetString("enter_registration_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter carrier, broker or dealer registration number.
        /// </summary>
        internal static string enter_registration_number_blank_error {
            get {
                return ResourceManager.GetString("enter_registration_number_blank_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a carrier, broker or dealer registration with numbers and letters. For example, CBDU 123456.
        /// </summary>
        internal static string enter_registration_number_error {
            get {
                return ResourceManager.GetString("enter_registration_number_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier, broker or dealer registration numbers must be less than 16 characters.
        /// </summary>
        internal static string enter_registration_number_error_max_characters {
            get {
                return ResourceManager.GetString("enter_registration_number_error_max_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier, broker or dealer registration numbers must contain less than 10 letters.
        /// </summary>
        internal static string enter_registration_number_error_max_letters {
            get {
                return ResourceManager.GetString("enter_registration_number_error_max_letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier, broker or dealer registration numbers must contain less than 10 numbers.
        /// </summary>
        internal static string enter_registration_number_error_max_numbers {
            get {
                return ResourceManager.GetString("enter_registration_number_error_max_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a carrier, broker or dealer registration with numbers and letters. For example, ROC UT 1234.
        /// </summary>
        internal static string nothernireland_enter_registration_number_error {
            get {
                return ResourceManager.GetString("nothernireland_enter_registration_number_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier, broker or dealer registration numbers must be less than 11 characters.
        /// </summary>
        internal static string nothernireland_enter_registration_number_error_max_characters {
            get {
                return ResourceManager.GetString("nothernireland_enter_registration_number_error_max_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier, broker or dealer registration numbers must contain less than 10 letters.
        /// </summary>
        internal static string nothernireland_enter_registration_number_error_max_letters {
            get {
                return ResourceManager.GetString("nothernireland_enter_registration_number_error_max_letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier, broker or dealer registration numbers must contain less than 6 numbers.
        /// </summary>
        internal static string nothernireland_enter_registration_number_error_max_numbers {
            get {
                return ResourceManager.GetString("nothernireland_enter_registration_number_error_max_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a reprocessor of UK packaging waste. Waste carrier, broker or dealer registration.
        /// </summary>
        internal static string page_description {
            get {
                return ResourceManager.GetString("page_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste carrier, broker or dealer registration.
        /// </summary>
        internal static string page_title {
            get {
                return ResourceManager.GetString("page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select if you have a Waste carrier, broker or dealer registration.
        /// </summary>
        internal static string select_registration_error {
            get {
                return ResourceManager.GetString("select_registration_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste carrier, broker or dealer registration for: {0}.
        /// </summary>
        internal static string waste_carrier_broker_dealer_registration {
            get {
                return ResourceManager.GetString("waste_carrier_broker_dealer_registration", resourceCulture);
            }
        }
    }
}
