//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.Registration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CheckYourAnswersWasteDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CheckYourAnswersWasteDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.Registration.CheckYourAnswersWasteDet" +
                            "ails", typeof(CheckYourAnswersWasteDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your answers before continuing.
        /// </summary>
        public static string heading {
            get {
                return ResourceManager.GetString("heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a reprocessor of UK packaging waste. Check your answers for waste permits.
        /// </summary>
        public static string page_description {
            get {
                return ResourceManager.GetString("page_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your answers for waste permits.
        /// </summary>
        public static string page_title {
            get {
                return ResourceManager.GetString("page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per year, month or week.
        /// </summary>
        public static string summary_list_generic_period_key {
            get {
                return ResourceManager.GetString("summary_list_generic_period_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum weight the permit authorises the site to accept and recycle (tonnes).
        /// </summary>
        public static string summary_list_maximum_weight_permit_tonnes_key {
            get {
                return ResourceManager.GetString("summary_list_maximum_weight_permit_tonnes_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum weight the site is currently capable of reprocessing (tonnes).
        /// </summary>
        public static string summary_list_maximum_weight_site_tonnes_key {
            get {
                return ResourceManager.GetString("summary_list_maximum_weight_site_tonnes_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the selected materials.
        /// </summary>
        public static string summary_list_packaging_details_change_link_aria_text {
            get {
                return ResourceManager.GetString("summary_list_packaging_details_change_link_aria_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging waste the site has a permit or exemption to accept and recycle.
        /// </summary>
        public static string summary_list_packaging_details_key {
            get {
                return ResourceManager.GetString("summary_list_packaging_details_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit for accepting and reprocessing {0}.
        /// </summary>
        public static string summary_list_permit_sub_heading {
            get {
                return ResourceManager.GetString("summary_list_permit_sub_heading", resourceCulture);
            }
        }
    }
}
