//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.Registration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ManualAddressForReprocessingSite {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManualAddressForReprocessingSite() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.Registration.ManualAddressForReproces" +
                            "singSite", typeof(ManualAddressForReprocessingSite).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprocessing site address.
        /// </summary>
        internal static string ManualAddressForReprocessingSitePageTitle {
            get {
                return ResourceManager.GetString("ManualAddressForReprocessingSitePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site grid reference.
        /// </summary>
        internal static string SiteGridReference {
            get {
                return ResourceManager.GetString("SiteGridReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ll find the site grid reference on permits and exemptions.
        /// </summary>
        internal static string SiteGridReferenceHint {
            get {
                return ResourceManager.GetString("SiteGridReferenceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User enters more than 10 digits.
        /// </summary>
        internal static string ValidationMessage_SiteGridReference_MaxLength {
            get {
                return ResourceManager.GetString("ValidationMessage_SiteGridReference_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a grid reference with at least 4 numbers.
        /// </summary>
        internal static string ValidationMessage_SiteGridReference_MinLength {
            get {
                return ResourceManager.GetString("ValidationMessage_SiteGridReference_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter the site’s grid reference.
        /// </summary>
        internal static string ValidationMessage_SiteGridReference_Required {
            get {
                return ResourceManager.GetString("ValidationMessage_SiteGridReference_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  User enters only letters and/or special characters.
        /// </summary>
        internal static string ValidationMessage_SiteGridReference_SpecialCharacters {
            get {
                return ResourceManager.GetString("ValidationMessage_SiteGridReference_SpecialCharacters", resourceCulture);
            }
        }
    }
}
