//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.Registration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MaximumWeightSiteCanReprocess {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaximumWeightSiteCanReprocess() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.Registration.MaximumWeightSiteCanRepr" +
                            "ocess", typeof(MaximumWeightSiteCanReprocess).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select if the weight that can be reprocessed is per year, per month or per week.
        /// </summary>
        internal static string frequency_option_required_error_message {
            get {
                return ResourceManager.GetString("frequency_option_required_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this per year, per month or per week?.
        /// </summary>
        internal static string frequency_options_label_text {
            get {
                return ResourceManager.GetString("frequency_options_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum weight of {0} packaging waste the site is currently capable of reprocessing.
        /// </summary>
        internal static string heading_text {
            get {
                return ResourceManager.GetString("heading_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum weight of {0} packaging waste the site could reprocess.
        /// </summary>
        internal static string maximum_weight_label_text {
            get {
                return ResourceManager.GetString("maximum_weight_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the maximum weight the site could reprocess.
        /// </summary>
        internal static string maximum_weight_required_error_message {
            get {
                return ResourceManager.GetString("maximum_weight_required_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a reprocessor of UK packaging waste. Maximum weight the site is capable of reprocessing.
        /// </summary>
        internal static string page_description {
            get {
                return ResourceManager.GetString("page_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum weight the site is capable of reprocessing.
        /// </summary>
        internal static string page_title {
            get {
                return ResourceManager.GetString("page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of packaging waste the site could reprocess when operating to full capacity. This is the capacity it could reach using the existing plant and equipment..
        /// </summary>
        internal static string paragraph1_text {
            get {
                return ResourceManager.GetString("paragraph1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per month.
        /// </summary>
        internal static string per_month {
            get {
                return ResourceManager.GetString("per_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per week.
        /// </summary>
        internal static string per_week {
            get {
                return ResourceManager.GetString("per_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per year.
        /// </summary>
        internal static string per_year {
            get {
                return ResourceManager.GetString("per_year", resourceCulture);
            }
        }
    }
}
