//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.Registration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProvideGridReferenceOfReprocessingSite {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProvideGridReferenceOfReprocessingSite() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.Registration.ProvideGridReferenceOfRe" +
                            "processingSite", typeof(ProvideGridReferenceOfReprocessingSite).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address manually.
        /// </summary>
        public static string enter_address_manually {
            get {
                return ResourceManager.GetString("enter_address_manually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the reprocessing site’s grid reference.
        /// </summary>
        public static string enter_site_grid_reference {
            get {
                return ResourceManager.GetString("enter_site_grid_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the site’s grid reference.
        /// </summary>
        public static string enter_site_grid_reference_error_message {
            get {
                return ResourceManager.GetString("enter_site_grid_reference_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid reference.
        /// </summary>
        public static string grid_reference {
            get {
                return ResourceManager.GetString("grid_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid references must include numbers.
        /// </summary>
        public static string grid_reference_must_include_numbers_error_message {
            get {
                return ResourceManager.GetString("grid_reference_must_include_numbers_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a reprocessor of UK packaging waste. Reprocessing site grid reference.
        /// </summary>
        public static string grid_reference_page_description {
            get {
                return ResourceManager.GetString("grid_reference_page_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the reprocessing site’s grid reference.
        /// </summary>
        public static string grid_reference_page_title {
            get {
                return ResourceManager.GetString("grid_reference_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a grid reference with at least 4 numbers.
        /// </summary>
        public static string grid_reference_with_at_least_4_characters_error_message {
            get {
                return ResourceManager.GetString("grid_reference_with_at_least_4_characters_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a grid reference with no more than 10 numbers.
        /// </summary>
        public static string grid_reference_with_no_more_than_10_characters_error_message {
            get {
                return ResourceManager.GetString("grid_reference_with_no_more_than_10_characters_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ll find the site grid reference on permits and exemptions.
        /// </summary>
        public static string site_grid_reference_hint_text {
            get {
                return ResourceManager.GetString("site_grid_reference_hint_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a different address.
        /// </summary>
        public static string use_a_different_address {
            get {
                return ResourceManager.GetString("use_a_different_address", resourceCulture);
            }
        }
    }
}
