//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.Registration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProvideWasteManagementLicense {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProvideWasteManagementLicense() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.Registration.ProvideWasteManagementLi" +
                            "cense", typeof(ProvideWasteManagementLicense).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter licence number.
        /// </summary>
        internal static string error_message_enter_license_number {
            get {
                return ResourceManager.GetString("error_message_enter_license_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter permit or licence number.
        /// </summary>
        internal static string error_message_enter_permit_or_license_number {
            get {
                return ResourceManager.GetString("error_message_enter_permit_or_license_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this per year, per month or per week?.
        /// </summary>
        internal static string is_this_per_year_month_weekly {
            get {
                return ResourceManager.GetString("is_this_per_year_month_weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a reprocessor of UK packaging waste. Waste management licence.
        /// </summary>
        internal static string page_description {
            get {
                return ResourceManager.GetString("page_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste management licence.
        /// </summary>
        internal static string page_title {
            get {
                return ResourceManager.GetString("page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum weight of {0} the licence authorises the site to accept and recycle.
        /// </summary>
        internal static string the_maximum_weight_of_material_the_license_authorises {
            get {
                return ResourceManager.GetString("the_maximum_weight_of_material_the_license_authorises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste management licence.
        /// </summary>
        internal static string waste_management_license {
            get {
                return ResourceManager.GetString("waste_management_license", resourceCulture);
            }
        }
    }
}
