//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.Registration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SelectAuthorisationType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SelectAuthorisationType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.Registration.SelectAuthorisationType", typeof(SelectAuthorisationType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter licence number.
        /// </summary>
        public static string enter_license_number {
            get {
                return ResourceManager.GetString("enter_license_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter permit number.
        /// </summary>
        public static string enter_permit_number {
            get {
                return ResourceManager.GetString("enter_permit_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter permit or licence number.
        /// </summary>
        public static string enter_permit_or_license_number {
            get {
                return ResourceManager.GetString("enter_permit_or_license_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmental permit or waste management licence.
        /// </summary>
        public static string environmental_permit {
            get {
                return ResourceManager.GetString("environmental_permit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter licence number.
        /// </summary>
        public static string error_message_enter_license_number {
            get {
                return ResourceManager.GetString("error_message_enter_license_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter permit number.
        /// </summary>
        public static string error_message_enter_permit_number {
            get {
                return ResourceManager.GetString("error_message_enter_permit_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter permit or licence number.
        /// </summary>
        public static string error_message_enter_permit_or_license_number {
            get {
                return ResourceManager.GetString("error_message_enter_permit_or_license_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the type of permit the site has for accepting and recycling this waste.
        /// </summary>
        public static string error_message_no_selection {
            get {
                return ResourceManager.GetString("error_message_no_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a permit number in the correct format, like EPR/AB1234CD.
        /// </summary>
        public static string error_message_permit_number_format {
            get {
                return ResourceManager.GetString("error_message_permit_number_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste exemption.
        /// </summary>
        public static string exemption_references {
            get {
                return ResourceManager.GetString("exemption_references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation permit.
        /// </summary>
        public static string installation_permit {
            get {
                return ResourceManager.GetString("installation_permit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a reprocessor of UK packaging waste. Type of permit the site has for accepting and recycling waste materials.
        /// </summary>
        public static string page_description {
            get {
                return ResourceManager.GetString("page_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of permit the site has for accepting and recycling waste materials.
        /// </summary>
        public static string page_title {
            get {
                return ResourceManager.GetString("page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollution, Prevention and Control (PPC) permit.
        /// </summary>
        public static string pollution_prevention_and_control_permit {
            get {
                return ResourceManager.GetString("pollution_prevention_and_control_permit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste management licence.
        /// </summary>
        public static string waste_management_licence {
            get {
                return ResourceManager.GetString("waste_management_licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which type of permit does the site have for accepting and recycling {0}?.
        /// </summary>
        public static string which_type_of_permit_does_the_site_have_for_accepting_and_recycling {
            get {
                return ResourceManager.GetString("which_type_of_permit_does_the_site_have_for_accepting_and_recycling", resourceCulture);
            }
        }
    }
}
