//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.Registration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TaskList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.Registration.TaskList", typeof(TaskList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task List.
        /// </summary>
        public static string RxExRegistrationTaskList_PageTitle {
            get {
                return ResourceManager.GetString("RxExRegistrationTaskList.PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprocessing inputs and outputs.
        /// </summary>
        public static string RxExRegistrationTaskList_ReprocessingInputsAndOutputs {
            get {
                return ResourceManager.GetString("RxExRegistrationTaskList.ReprocessingInputsAndOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling and inspection plan per material.
        /// </summary>
        public static string RxExRegistrationTaskList_SamplingAndInspectionPlanPerMateria {
            get {
                return ResourceManager.GetString("RxExRegistrationTaskList.SamplingAndInspectionPlanPerMateria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site address and contact details.
        /// </summary>
        public static string RxExRegistrationTaskList_SiteAddressAndContactDetails {
            get {
                return ResourceManager.GetString("RxExRegistrationTaskList.SiteAddressAndContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a reprocessor of UK packaging waste
        ///.
        /// </summary>
        public static string RxExRegistrationTaskList_Title {
            get {
                return ResourceManager.GetString("RxExRegistrationTaskList.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete each section then submit your application to the regulator. You can save your progress and come back to it at any time..
        /// </summary>
        public static string RxExRegistrationTaskList_Title_Hint {
            get {
                return ResourceManager.GetString("RxExRegistrationTaskList.Title.Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste licenses, permits and exemptions.
        /// </summary>
        public static string RxExRegistrationTaskList_WasteLicensesPermitsAndExemptions {
            get {
                return ResourceManager.GetString("RxExRegistrationTaskList.WasteLicensesPermitsAndExemptions", resourceCulture);
            }
        }
    }
}
