//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epr.Reprocessor.Exporter.UI.Resources.Views.Registration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WastePermitExemptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WastePermitExemptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epr.Reprocessor.Exporter.UI.Resources.Views.Registration.WastePermitExemptions", typeof(WastePermitExemptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a reprocessor of UK packaging waste. Select materials the site is authorised to recycle.
        /// </summary>
        public static string page_description {
            get {
                return ResourceManager.GetString("page_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select materials the site is authorised to recycle.
        /// </summary>
        public static string page_title {
            get {
                return ResourceManager.GetString("page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to tell us all the materials the site has authorisation to accept and recycle..
        /// </summary>
        public static string waste_permit_exemptions_description_1 {
            get {
                return ResourceManager.GetString("waste_permit_exemptions_description_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ‘R’ code is the classification of the reprocessing activity. These are in Annex 2 of the.
        /// </summary>
        public static string waste_permit_exemptions_description_2a {
            get {
                return ResourceManager.GetString("waste_permit_exemptions_description_2a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Framework Directive (opens in new tab).
        /// </summary>
        public static string waste_permit_exemptions_description_2b {
            get {
                return ResourceManager.GetString("waste_permit_exemptions_description_2b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging waste the site has a permit or exemption to accept and recycle.
        /// </summary>
        public static string waste_permit_exemptions_heading {
            get {
                return ResourceManager.GetString("waste_permit_exemptions_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all the material categories the site has a permit or exemption to accept and recycle.
        /// </summary>
        public static string waste_permit_exemptions_sub_heading {
            get {
                return ResourceManager.GetString("waste_permit_exemptions_sub_heading", resourceCulture);
            }
        }
    }
}
